name: Test job
on:
  push:
    branches:
      - rchiodo/test_from_json

jobs:
  build-vsix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Test output
        run: echo "Some Output"
