name: 'Set Python'
description: "Sets python to a specific version"

inputs:
  IS_CONDA_ENV:
     description: 'Whether we are using a conda environment'
     required: false
     default: false
  PYTHON_VERSION:
     description: 'Version of python'
     required: true
     default: python
outputs:
  CI_PYTHON_PATH:
    description: 'Path to the python'
    value: ${{ steps.python_run.outputs.python_path }}
runs:
  using: 'composite'
  steps:
    - name: Output python path
      if: ${{ inputs.IS_CONDA_ENV == true }}
      id: python_run_conda
      # Use `bash -l {0}` when using the conda actions.
      shell: bash -l {0}
      run: python -c "import sys;print('::set-output name=python_path::' + sys.executable)"

    - name: Push to environment
      if: ${{ inputs.IS_CONDA_ENV == true }}
      # Use `bash -l {0}` when using the conda actions.
      shell: bash -l {0}
      run: echo "CI_PYTHON_PATH=${{ steps.python_run_conda.outputs.python_path }}" >> $GITHUB_ENV

    - name: Output python path
      if: ${{ inputs.IS_CONDA_ENV == false }}
      id: python_run
      shell: bash
      run: python -c "import sys;print('::set-output name=python_path::' + sys.executable)"

    - name: Push to environment
      if: ${{ inputs.IS_CONDA_ENV == false }}
      shell: bash
      run: echo "CI_PYTHON_PATH=${{ steps.python_run.outputs.python_path }}" >> $GITHUB_ENV
