codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 0
  round: down
  range: '70...100'

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'header, diff, files'
  behavior: default
  require_changes: no

fixes:
  # Remove prefix in coverage report
  - '/home/runner/work/vscode-jupyter/::'
