version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: daily
    labels:
      - 'skip news'

  - package-ecosystem: 'pip'
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: 'pip'
    directory: /news
    schedule:
      interval: monthly
    labels:
      - 'skip news'
  # Activate when we feel ready to keep up with frequency.
  # - package-ecosystem: 'npm'
  #   directory: /
  #   schedule:
  #     interval: daily
