FROM amd64/python
# FROM amd64/alpine:3.15

# RUN apk add git curl

# ENV PYTHONUNBUFFERED=1
# RUN apk add --no-cache python3 py3-pip
# RUN python3 -m ensurepip
# RUN python3 -m pip install ipykernel
