name: 'Create Virtual Environment'
description: 'Create Virtual Env for tests'

inputs:
  IPyWidgetVersion:
    description: 'Version of IPyWidgets'
    required: false
    default: '7'

outputs:
  path:
    description: 'Path to the VSIX'
    value: 'ms-toolsai-jupyter-insiders.vsix'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6

    # Used by tests for installation of ipykernel.
    # Create a venv & register it as a kernel.
    # These tests are slow hence will only run on linux.
    # This env will be used to install ipykernel & test for prompts if ipykernel is missing & imilar tests.
    # Ensure this is registered as a kernel.
    # Use specific version of Jedi https://github.com/ipython/ipython/issues/12740
    - name: Create virtual environment without ipykernel
      if: inputs.IPyWidgetVersion == '7'
      run: |
        uv venv .venvnoreg
        uv venv .venvkernel
        source .venvnoreg/bin/activate
        uv pip install pip
        source .venvkernel/bin/activate
        python --version
        python -c "import sys;print(sys.executable)"
        uv pip install pip
        uv pip install ipykernel
        python -m ipykernel install --user --name .venvkernel --display-name .venvkernel
        uv pip install pandas
        uv pip install ipywidgets==7.7.2

        uv venv .venvnokernel
        source .venvnokernel/bin/activate
        python --version
        python -c "import sys;print(sys.executable)"
        uv pip install pip
        uv pip install ipykernel
        python -m ipykernel install --user --name .venvnokernel --display-name .venvnokernel
      working-directory: src/test/datascience
      shell: bash
    # Used by tests for installation of ipykernel.
    # Create a venv & register it as a kernel.
    # These tests are slow hence will only run on linux.
    # This env will be used to install ipykernel & test for prompts if ipykernel is missing & imilar tests.
    # Ensure this is registered as a kernel.
    # Use specific version of Jedi https://github.com/ipython/ipython/issues/12740
    - name: Create virtual environment without ipykernel (ipywidgets 8)
      if: inputs.IPyWidgetVersion == '8'
      run: |
        uv venv .venvnoreg
        uv venv .venvkernel
        source .venvnoreg/bin/activate
        uv pip install pip
        source .venvkernel/bin/activate
        python --version
        python -c "import sys;print(sys.executable)"
        uv pip install pip
        uv pip install ipykernel
        python -m ipykernel install --user --name .venvkernel --display-name .venvkernel
        uv pip install pandas
        uv pip install ipywidgets -U

        uv venv .venvnokernel
        source .venvnokernel/bin/activate
        python --version
        python -c "import sys;print(sys.executable)"
        uv pip install pip
        uv pip install ipykernel
        python -m ipykernel install --user --name .venvnokernel --display-name .venvnokernel
      working-directory: src/test/datascience
      shell: bash
