name: 'Create Virtual Environment'
description: "Create Virtual Env for tests"

outputs:
  path:
    description: 'Path to the VSIX'
    value: 'ms-toolsai-jupyter-insiders.vsix'

runs:
  using: 'composite'
  steps:
    # Used by tests for installation of ipykernel.
    # Create a venv & register it as a kernel.
    # These tests are slow hence will only run on linux.
    # This env will be used to install ipykernel & test for prompts if ipykernel is missing & imilar tests.
    # Ensure this is registered as a kernel.
    - name: Create virtual environment without ipykernel
      run: |
        python -m venv .venvnokernel
        source .venvnokernel/bin/activate
        python -m pip install ipykernel
        python -m ipykernel install --user --name .venvnokernel --display-name .venvnokernel
        python -m pip uninstall ipykernel --yes
      working-directory: src/test/datascience
      shell: bash
