name: 'Build VSIX'
description: "Build the extension's VSIX"

outputs:
  path:
    description: 'Path to the VSIX'
    value: 'ms-toolsai-jupyter-insiders.vsix'

runs:
  using: 'composite'
  steps:
    - run: npm ci --prefer-offline
      env:
        npm_config_build_from_source: true
      shell: bash

    # Run again, as the download of zmq binaries could have failed with 403 errors
    - run: npm run postinstall
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash

    - run: npm run package
      shell: bash
