name: 'Build VSIX'
description: "Build the extension's VSIX"

outputs:
  path:
    description: 'Path to the VSIX'
    value: 'ms-toolsai-jupyter-insiders.vsix'

runs:
  using: 'composite'
  steps:
    - run: npm ci --prefer-offline
      shell: bash

    - run: npm run package
      shell: bash
