name: 'Build VSIX'
description: "Build the extension's VSIX"

outputs:
  path:
    description: 'Path to the VSIX'
    value: 'ms-ai-tools-jupyter-insiders.vsix'

runs:
  using: 'composite'
  steps:
    - run: npm ci --prefer-offline
      shell: bash

    # Use the GITHUB_RUN_ID environment variable to update the build number.
    # GITHUB_RUN_ID is a unique number for each run within a repository.
    # This number does not change if you re-run the workflow run.
    - name: Update build number
      run: npm run updateBuildNumber -- --buildNumber $GITHUB_RUN_ID
      shell: bash

    # Update change log (for release notes).
    # - run: npm run updateBuildNumber -- --buildNumber $GITHUB_RUN_ID --updateChangelog
    #   shell: bash

    - run: npm run package
      shell: bash
