name: 'Build VSIX'
description: "Build the extension's VSIX"

outputs:
  path:
    description: 'Path to the VSIX'
    value: 'ms-toolsai-jupyter-insiders.vsix'

runs:
  using: 'composite'
  steps:
    # This is faster than running `npm ci`, we do not want to build zmq, as its already built by us.
    - run: npm ci --ignore-scripts --prefer-offline --no-audit
      shell: bash

    # Run again, as the download of zmq binaries could have failed with 403 errors
    - run: npm run postinstall
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash

    - run: npm run package
      shell: bash
