name: 'Install dependencies (npm ci)'
description: "npm install (with GITHUB_TOKEN to run postinstall step)"

runs:
  using: 'composite'
  steps:
    - run: npm ci --foreground-scripts --prefer-offline
      env:
        npm_config_build_from_source: true
      shell: bash

    # Run again, as the download of zmq binaries could have failed with 403 errors
    - run: npm run postinstall
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
