name: Apply label for opened issues

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  # From https://github.com/marketplace/actions/github-script#apply-a-label-to-an-issue.
  add-triage-needed-label:
    name: "Add 'triage-needed'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7.0.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['triage-needed']
            })
