# Temporary file to test out writing to a branch during a PR
name: Verify perf test

permissions:
  deployments: write

on:
  pull_request:
    branches:
      - main

jobs:
  perf-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create local changes
      run: |
        echo ${{ github.sha }} > ./build/ci/performance/perf-results.txt
    - name: Commit files
      run: |
        git commit -m "Update perf results" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}