# Temporary file to test out writing to a branch during a PR
name: Verify perf test

permissions:
  deployments: write

on:
  pull_request:
    branches:
      - main

jobs:
  perf-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        ref: ${{ github.event.pull_request.head.ref }}
    - id: read_old_results
      name: Read old results into an output
      shell: bash -l {0}
      run: |
        content=`cat ./build/ci/performance/perf-results.json`
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=content::$content"
        
    - id: test_make_change
      name: Test if need to make changes
      shell: bash -l {0}
      run: |
        # end of optional handling for multi line json
        if ("${{fromJson(steps.read_old_results.outputs.content).head_ref}}" != "${{github.head_ref}}") || (${{fromJson(steps.read_old_results.outputs.content).run_number}} < ${{github.run_number}})
        then
           echo "::set-output name=shouldMakeChange::true"
        else
           echo "::set-output name=shouldMakeChange::false"
        fi
        echo "::set-output name=nextRunNumber::$((${{github.run_number}}+1))"

    - name: Create local changes
      if: ${{ steps.test_make_change.outputs.shouldMakeChange}}
      uses: jsdaniell/create-json@1.1.2
      with:
        name: 'perf-results.json'
        dir: './build/ci/performance'
        json: '{ "run_number": ${{ steps.test_make_change.outputs.nextRunNumber }}, "head_ref": "${{github.head_ref}}", "results": {} }'
    - name: Commit files
      if: ${{ steps.test_make_change.outputs.shouldMakeChange}}
      run: |
        git config --local user.email "41898282+github-actions@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update perf results" -a
    - name: Push changes
      if: ${{ steps.test_make_change.outputs.shouldMakeChange}}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERF_UPLOAD_TOKEN_LL }}
        branch: ${{ github.event.pull_request.head.ref }}