name: Repository Dispatch
on:
  repository_dispatch:
    types: [build-vsix]

jobs:
  build-vsix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Test output
        run: echo "${{ github.event.client_payload.payload }}" 
