// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

export const ACTIVATION_TIMES_DEV_LOG_FILE_PATHS = process.env.ACTIVATION_TIMES_DEV_LOG_FILE_PATHS;
export const ACTIVATION_TIMES_EXT_VERSION = process.env.ACTIVATION_TIMES_EXT_VERSION;
export const ACTIVATION_TIMES_RELEASE_LOG_FILE_PATHS = process.env.ACTIVATION_TIMES_RELEASE_LOG_FILE_PATHS;
export const ACTIVATION_TIMES_DEV_LANGUAGE_SERVER_LOG_FILE_PATHS =
    process.env.ACTIVATION_TIMES_DEV_LANGUAGE_SERVER_LOG_FILE_PATHS;

export const ACTIVATION_TIMES_LOG_FILE_PATH = process.env.ACTIVATION_TIMES_LOG_FILE_PATH;
